### ISSUE TITLE
Amazing work buddy. I wish I could do more than yes or no

### ISSUE THREAD

**Issue by dibyadip-das** [keatontaylor/alexa-actions#11]
@keatontaylor , you have done amazing work. This is mind-blowing. I did integrate, and it works flawlessly. I wish there was a way to have custom options more than yes and no.

For e.g.
I turn on the TV and I am greeted with a message, "I see you turned on the tv. Would you like to watch Youtube, Netflix, or Hulu ?" I hope this example makes the scenario clear.

Anyways thanks dude for your hard work! Really appreciate your work.

**Comment by keatontaylor** [comment]
This would absolutely be an awesome addition and I have considered it. Technically speaking, it is possible, but you'd need to modify the custom skill code to add slot types and new intents to handle these interactions. 

Since these slot types and intents would be unique to each person who sets up the skill, it is hard to implement some functionality that would be universal and so I fell back on simply providing ResponseYes/ResponseNo/ResponseNone, since the Yes and No intent are fairly universal.

What I've done for now is add to the Wiki a [Advanced Features](https://github.com/keatontaylor/alexa-actions/wiki/AdvancedFeatures) section to be a placeholder for guides pertaining to adding such functionality.  

Thank you for the suggestion and keep a lookout on the [Advanced Features](https://github.com/keatontaylor/alexa-actions/wiki/AdvancedFeatures). I'll try to get a guide on a simple setup for what you've described soon.
