### ISSUE TITLE
AWS Lambda  Function integration with Nabu Casa issue

### ISSUE THREAD

**Issue by MFaro** [keatontaylor/alexa-actions#124]
Do you know if  it is possible to create the function using  Nabu Casa integration?   After creating the Lambda Function, following the steps described in the Wiki page, I entered the environment variables: BASE_URL  and NOT_VERIFY_SSL, I received the  error message:

HTTPSConnectionPool(host='xxxxxxxxxx.ui.nabu.casa', port=443): Max retries exceeded with url: /api/alexa (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

Does anyone have any suggestions on how to resolve this issue? I’m running the latest version of Home Assistant Operating System: Home Assistant:

**Comment by DEADSEC-SECURITY** [comment]
Where did you get the `NOT_VERIFY_SSL`? If you don't want SSL the option `VERIFY_SSL = True ` should be set to `VERIFY_SSL = False`

**Comment by MFaro** [comment]
I tried both options VERIFY_SSL = True and False,, but the error is the same.  Thanks for your comment.

**Comment by DEADSEC-SECURITY** [comment]
Is your firewall/router blocking connections from amazon?

**Comment by DeckardKane** [comment]
I apologize, I don't know if resurrecting this issue is good form, but I figured it'd be better than making a duplicate.

I am experiencing a similar issue. Oddly, it's an intermittent one, sometimes responses fire without any problems, but every now and then I get a "There was a problem with the requested skill response". I've checked the CloudWatch logs, and I get pretty much the same error as the OP every time:

MaxRetryError: HTTPSConnectionPool(host='xxxxxxxxxxxx.ui.nabu.casa', port=443): Max retries exceeded with url: /api/states/input_text.alexa_actionable_notification (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1091)')))

This occurs regardless of whether or not SSL verification is enabled (I do get a separate warning "strongly advising" the use of SSL, of course).

Like I said, I _do_ get successful actionable notifications fairly frequently. I'd estimate one out of every ten or so actions fails in this manner? 

It's entirely possible that this issue is not caused by anything on your end (I wonder if this issue would go away if I went back to DuckDNS?). Either way, I figured I'd report my findings here.
