### ISSUE TITLE
Problem to Import Model

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [keatontaylor/alexa-actions#177]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

Hi when i try to import model from github into alexa it's show me 

`There was an issue creating your skill. Skill resources were not provisioned. Please try again later.`

### Version

Latest

### What Alexa device are you using?

Echo

**Comment by MattiaFontanaErrepinet** [comment]
After various test i have find problem: 
The problem is caused by this piece of code

`  {
          "name": "String",
          "slots": [
            {
              "name": "Strings",
              "type": "AMAZON.SearchQuery"
            }
          ],
          "samples": [
            " {Strings}"
          ]
        },`

**Comment by DEADSEC-SECURITY** [comment]
Ill take a look tomorrow @MattiaFontanaErrepinet , thanks for reporting

**Comment by level451** [comment]
Same issue - any work around?
Thanks

**Comment by whubbartt** [comment]
It's not a fix, but version 0.8.2 works good

**Comment by marloncarvalho** [comment]
Same issue here too. Waiting for workarounds until a patch is released.

**Comment by akela-it** [comment]
Same issue here too. 

Error:
Change skill invocation name
Your skill name cannot be used as an invocation name. A default invocation name is set till you change it.

**Comment by marloncarvalho** [comment]
As @MattiaFontanaErrepinet said, the issue is in the line  { "name": "String", "slots": [ { "name": "Strings", "type": "AMAZON.SearchQuery" } ], "samples": [ " {Strings}" ] }.

I got it working just adding a letter before {Strings} in the samples. For example:
 { "name": "String", "slots": [ { "name": "Strings", "type": "AMAZON.SearchQuery" } ], "samples": [ "hi {Strings}" ] }

To get it working, just fork this repository, go to skill-package/interactionModels/your-language.json and edit this file, adding something before {Strings}. Just remember to use your cloned Github repository as source to import the skill.

**Comment by level451** [comment]
Thanks! Adding the text did the trick

**Comment by Varguit** [comment]
It's happening the same to me even after adding a word before {Strings}.
Any updates on the setup method since then?
Can I start from scratch and import all the lambda files or is there something else I should do?
