### ISSUE TITLE
We are unable to link skill at this time

### ISSUE THREAD

**Issue by vijayvikma** [keatontaylor/alexa-actions#25]
Hello folks,

I am using https://layla.amazon.com/ Client Id from India since no instruction .may be not required. I am getting unable to link skill error.

I am using nabu casa url to excess my home assistant.

Please suggest

**Comment by keatontaylor** [comment]
Were you able to get past this, I have a few more troubleshooting steps you might be able to try.

**Comment by vijayvikma** [comment]
Please share the steps. For other Alexa skillS I am able to link account(gmail). Here it shows home assistant page while enabling but when gives error while logging. Is there any specific client ID for my region(India).

**Comment by keatontaylor** [comment]
You may try and do account linking from the https://alexa.amazon.com website. (This may be different for your region but should redirect) 

Once it redirects back to home assistant for you to login you can copy the URL from your browser and take a look at the redirect URL that it has in the long URL string. That is what you need to put into the custom skill.

**Comment by ceaswaran** [comment]
@vij

> Please share the steps. For other Alexa skillS I am able to link account(gmail). Here it shows home assistant page while enabling but when gives error while logging. Is there any specific client ID for my region(India).

@vijayvikma i too had issues in linking the account, I belong to Chennai India.
below are the few things I trouble shooted, now basic intitial testing works fine,which might help you I am not a expert but incase if you have not tried  these u can try 

1. My echo devices were set to **English (IN)** but logging into Amazon developer account & creating skill by default is **English (US)**  , I made sure I match the echoo devices language (IN) & deleted the (US) language in created skill & proceeded with all other as per @keatontaylor tutorial.

2. Client ID for India is https://layla.amazon.com/ (As per amazon documentation)

3. I am as of now successful using long-lived token ,method only & not Account linking method, hence try using long-lived token .

4. Keaton & One of my friend who is a developer helped me to understand this skill is taking longer time to get connected to HA, This may be due to router capabilites or ISP restrictions or amazon servers restrictions. (Not sure what exactly is the reason) but my friend looking at the code he asked me to change line No 72 
`FROM timeout=urllib3.Timeout(connect=10.0, read=10.0)  TO timeout=urllib3.Timeout(connect=5.0, read=5.0)`
 after which the skill is working fine. She responds as expected without any error. 

Hope it helps

**Comment by keatontaylor** [comment]
@vijayvikma where you able to get this working? If not please feel free to join our [discord channel](https://discord.gg/9A5qfa) #alexa-notifications

**Comment by vijayvikma** [comment]
Thank much folks. I will try updating line 72 and will see. But yeah if ISP involved/router involved in that , that will be pain for me to get it done 😁 Again thanks much for the help

**Comment by ceaswaran** [comment]
> Thank much folks. I will try updating line 72 and will see. But yeah if ISP involved/router involved in that , that will be pain for me to get it done 😁 Again thanks much for the help

Who is ur ISP?

**Comment by vijayvikma** [comment]
It’s GTPL and they provided us shared IP behind CG NAT

**Comment by ceaswaran** [comment]
ok

> It’s GTPL and they provided us shared IP behind CG NAT

not sure how i can help, 1. how you are accessing Home assistant from the outside world?
2. If you are ok home automation India telegram group will have someone who has solved this if they have faced the issue, i can add you there
