### ISSUE TITLE
Discord for General Q's

### ISSUE THREAD

**Issue by Pashovski** [keatontaylor/alexa-actions#53]
I feel like I'm still pretty new to the scene to be posting here, but the discord link isnt working. I'm not even getting to the linking part after enabling the skill, and I'm thinking it is because my home assistant URL is just http://192.168.10.230:8123 . Assuming the discord is no longer around, Should I put my nabu casa url in there instead?

**Comment by welbo97** [comment]
I'm pretty new too but did get it to work for a while. I used my nabu casa link with a trailing /auth/authorize and /auth/token in the skill setup on the amazon developer console. It looks to me like that link is whatever will get to your home assistant instance from the internet. But there is a warning that it will not work if your external url uses port :8123 rather than the standard https port of :443. So either you must have nabu casa set up, or a reverse proxy with https certificates that are valid, like you would get from lets encrypt or other CA.

**Comment by Pashovski** [comment]
Thanks! I can do the nabu casa url. Can you clarify what you mean by /auth/authorize and /auth/token ? I thought this meant that I would stuck this on at the end of my nabu casa url, but if there are two of them, I thought I should ask first.

**Comment by welbo97** [comment]
```
Under Authorization URI provide your home assistant URL followed by /auth/authorize (Example: https://myhomeassistant.com/auth/authorize
Under Access Token URI provide your home assistant URL followed by /auth/token (Example: https://myhomeassistant.com/auth/token)
```
That's out of the alexa actionable wiki instructions. They work very well if you follow them step by step. I had to read them several times before it sunk into my slow head though.

**Comment by Pashovski** [comment]
Thank you so much!!
