### ISSUE TITLE
Problem with response (YES, NO)

### ISSUE THREAD

**Issue by DOWIT-JoelFrojmowicz** [keatontaylor/alexa-actions#93]
If you are facing a problem with alexa response saying that she does not understand your command when you answer YES or NO.

Check if the user used on "Account Linking" have administrator rights!!

The installation guide should inform that the user must have administrator rights for this integration work.

**Comment by carvalr** [comment]
I would like to add some information to your comment.
If using long term token from HA instead of Account Linking, I recommend changing the lines showed below in the file "lambda_fuction.py". On this way any token setting related issue can be removed from equation.
![image](https://user-images.githubusercontent.com/74059823/130543995-e56c390f-6fa1-4293-9f16-e24305216b00.png)

**Comment by elkarto** [comment]
> If you are facing a problem with alexa response saying that she does not understand your command when you answer YES or NO.
> 
> Check if the user used on "Account Linking" have administrator rights!!
> 
> The installation guide should inform that the user must have administrator rights for this integration work.

It was driving me crazy.

Thanks!!!! I didn't know what else to try.

Now it works perfectly.
